version: '3'
services:
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

  app:
    build: .
    command: npm run dev
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 27017
      DB_NAME: taskdb
